-- CREATE DATABASE security_app_db1;
-- \c security_app_db1;

DROP TABLE IF EXISTS person;

CREATE TABLE person (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(256) NOT NULL,
    password VARCHAR(256) NOT NULL,
    year_of_birth INTEGER
);

INSERT INTO person (username, password, year_of_birth)
VALUES
('test_user1', 'qwerty', 2020),
('test_user2', 'qwerty', 2020);

CREATE EXTENSION IF NOT EXISTS pgcrypto;

UPDATE person
SET password=crypt(password, gen_salt('bf', 8))
WHERE password NOT LIKE '$%';
