version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    container_name: postgres_demo
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_USER: postgres
      POSTGRES_DB: testdb
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
