-- CREATE DATABASE first_db2;
-- \c first_db2

DROP TABLE IF EXISTS passport;
DROP TABLE IF EXISTS actor_movie;
DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS movie;
DROP TABLE IF EXISTS actor;

CREATE TABLE actor (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(256),
    age INTEGER
);

CREATE TABLE movie (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(256),
    year_of_production INTEGER
);

CREATE TABLE actor_movie (
    actor_id INTEGER REFERENCES actor(id),
    movie_id INTEGER REFERENCES movie(id),
    PRIMARY KEY (actor_id, movie_id)
);

CREATE TABLE item (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id INT REFERENCES actor(id) ON DELETE SET NULL,
    item_name VARCHAR(256)
);

CREATE TABLE passport (
    person_id INT PRIMARY KEY REFERENCES actor(id) ON DELETE CASCADE,
    passport_number INT
);
