
GET http://localhost:8080/api/commodity/v1/all


POST http://localhost:9001/api/discount
Content-Type: application/json

{
    "discountCode": "q123",
    "discountPercentage": 12
}


POST http://localhost:9001/api/order
Content-Type: application/json

{
    "orderLocation": "test1",
    "creditCardNumber": "test2",
    "items": [
        {
            "itemName": "plastic gloves",
            "price": 123,
            "quantity": 201
        }
    ]
}

POST http://localhost:9001/api/order
Content-Type: application/json

{
    "orderLocation": "test1",
    "creditCardNumber": "test2",
    "items": [
        {
            "itemName": "leather gloves",
            "price": 123,  
            "quantity": 123
        }
    ]
}

POST http://localhost:9001/api/order
Content-Type: application/json

{
    "orderLocation": "Country Fraud",
    "creditCardNumber": "test2",
    "items": [
        {
            "itemName": "leather gloves",
            "price": 123,
            "quantity": 123
        }
    ]
}


POST http://localhost:9001/api/promotion
Content-Type: application/json

{
    "promotionCode": "test123" 
}


POST http://localhost:9001/api/feedback
Content-Type: application/json

{
    "feedback": "Good feedback example 123",
    "location": "Location Example 123"
}

POST http://localhost:9001/api/feedback
Content-Type: application/json

{
    "feedback": "Bad feedback example 123",
    "location": "Location Example 123"
}

POST http://localhost:9001/api/feedback
Content-Type: application/json

{
    "feedback": "Neutral feedback example 123",
    "location": "Location Example 123"
}
