logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

spring:
  main:
    banner-mode: OFF
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      ack-mode: batch
    consumer:
      group-id: default-spring-consumer
      auto-offset-reset: earliest
      max-poll-records: 10
  jackson:
    date-format: yyyy-MMM-dd
