logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

spring:
  application:
    name: kafka-core-consumer
  main:
    banner-mode: OFF
    log-startup-info: false
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      ack-mode: batch
    consumer:
      group-id: default-spring-consumer
      auto-offset-reset: earliest
      max-poll-records: 10
    properties:
      metrics:
        num:
          samples: 4
      partition:
        assignment:
          strategy: org.apache.kafka.clients.consumer.RoundRobinAssignor
  jackson:
    date-format: yyyy-MMM-dd
