logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

spring:
  main:
    banner-mode: OFF
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: default-spring-consumer
      auto-offset-reset: earliest
  jackson:
    date-format: yyyy-MMM-dd
