-- CREATE DATABASE security_app_db1;
-- \c security_app_db1

DROP TABLE IF EXISTS person;

CREATE TABLE person (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(256) NOT NULL,
    password VARCHAR(256) NOT NULL,
    year_of_birth INTEGER
);

INSERT INTO person (username, password, year_of_birth)
VALUES
('test_user1', 'qwerty', 2020),
('test_user2', 'qwerty', 2020);
