services:
  kafka_server:
    container_name: kafka_server
    restart: unless-stopped
    environment:
      # - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka_server:9092,CONTROLLER://${DOCKER_HOST_IP:-127.0.0.1}:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka_server:9092,PLAINTEXT_HOST://${DOCKER_HOST_IP:-127.0.0.1}:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
    networks:
      - kafka-net
    ports:
      - "9092:9092"
    build:
      context: .
      dockerfile: kafka_server.Dockerfile
    volumes:
      - kafka_server_volume:/home/app_user/_kafka_data
  kafka_connect:
    container_name: kafka_connect
    restart: no
    environment:
      - CONNECT_BOOTSTRAP_SERVERS=kafka_server:9092
    networks:
      - kafka-net
    build:
      context: .
      dockerfile: kafka_connect.Dockerfile
    volumes:
      - kafka_connect_volume:/home/app_user/_kafka_data
    depends_on:
      - kafka_server

networks:
  kafka-net:
    name: kafka-net
    driver: bridge

volumes:
  kafka_server_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PROJECT_PATH}/docker-kafka-demo1/_data/kafka_server
  kafka_connect_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PROJECT_PATH}/docker-kafka-demo1/_data/kafka_connect
